//
// Created by nick on 05/08/25.
//

#ifndef STORAGE_ADDRESSES_H
#define STORAGE_ADDRESSES_H

#define BRIGHTNESS_INDEX_ADDR 0
#define BRIGHTNESS_VALUE1_ADDR 1
#define BRIGHTNESS_VALUE2_ADDR 2
#define BRIGHTNESS_VALUE3_ADDR 3

#endif //STORAGE_ADDRESSES_H
